
--Reiniciando la BD Endeavor



DELETE FROM gala_endeavor_2011_productos;
DELETE FROM gala_endeavor_2011_pujas;
DELETE FROM gala_endeavor_2011_usuarios;
DELETE FROM gala_endeavor_2011_alive;

INSERT INTO gala_endeavor_2011_usuarios ("user", nombre, mesa, tiempo_creacion) VALUES ('null', 'null', 0, '12/12/12');

INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (1, 'El Grande Reverso', 'El Grande Reverso luce una edición inédita de 30 x 48.5 mm y se caracteriza por su esfera plateada de espléndida sobriedad ornamentada con dígitos tradicionales del estilo Art Deco y un doble acabado: mientras el rectángulo del centro presenta un motivo guilloqueado con Clous de París, la parte exterior enarbola un acabado satinado. Ésta delicada alternancia ornamental se repite en el contador del segundero pequeño situado a las 6 horas. El Grande Reverso está animado por el nuevo Calibre 976, visible a través del fondo de cristal de zafiro. Posee todas las características de los movimientos robustos y precisos desarrollados por la manufactura Jaeger-LeCoultre y está equipado con un volante de inercia variable que palpita con una frecuencia de 28,800 alternancias por hora.', 7855.00, 7855.00, 7855.00, 'null');
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (2, 'Collar Peyrelongue', 'Collar Oro Rojo y Blanco\\n\\nKilataje Oro: 18K\\nKilataje Diamantes: 1.64 ct', 8500.00, 8500.00, 8500, 'null');
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (3, 'Collar Infinito Rosé', 'Collar de la Colección Infinito Elite Rosé\\n\\nPlata .925\\nBaño de Oro Rosa de 22K\\nZirconias montadas en Pavé', 2500.00, 2500.00, 2500.00, 'null');
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (4, 'Margie', 'La Margie es una motocicleta tipo Bobber de cuadro rígido, con suspensión frontal tipo Springer, asiento en piel terminado a mano, Motor 125 cc de 4 tiempos, de 4 velocidades y 7.5 caballos de fuerza y una velocidad de más de 100km/hr.\\nLas Margies son motocicletas urbanas con cambio semiautomático en tipo Shifter y Jockey haciéndola totalmente clásica, esto aunado a una suspensión de resorte trasero fabricado en acero pulido y cromado montado en un asiento de inyección de poliuretano con base de gel para reducir el impacto en la columna.\\nCuenta con llanta delantera de 18 pulgadas con freno de disco y atrás llanta de 15 Pulgadas con freno de tambor.\\nEncendido eléctrico y de patada, batería de seis celdas libre de mantenimiento.', 12000.00, 12000.00, 12000.00, 'null');
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (5, 'Johnnie Walker Blue Label', 'Johnnie Walker Blue Label: King George V Edition, celebra la primera Orden Real dada a la compañia John Walker and Sons Ltda., para proveer Scotch whisky a la Casa Real Británica, en 1934. Haciendo honor a su herencia, ésta exquisita mezcla ha sido hecha a mano utilizando las técnicas de la época, y usando whiskies de las destilerías que operaban durante el reinado de George V.\\n\\nCaracterísticas:\\n-Olfato: un aroma inicial profundamente ahumado seguido de una dulce y afrutada sensación (a manzanas, peras, bananas) propia de las maltas; que desemboca en una complejidad rica en frutos secos y especiados (uvas, pasas, higos, canela).\\n-Paladar: suave, con una rica y afrutada dulzura. Calienta el paladar con sutiles sabores a madera de sándalo y humo.\\n-Sabor: fuerte, complejo, rico y suave.\\n-Sensación final: cálido en la boca con un prolongado final rico en turba.\\n-Con Agua: libera nuevos sabores más frescos y afrutados, y deja una sensación ahumada en el paladar.', 615.00, 615.00, 615.00, 'null');
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (6, '528iA de Lujo', 'Alpine White/Leather Dakota Cinnamon Brown\\nChasis:C859775\\n\\nValor comercial: 56,300 USD\\n*El tiempo de entrega del coche será de al menos 15 días.', 46531.00, 46531.00, 46531.00, 'null') ;
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (7, 'Subasta de Oro', 'Collar de Oro Tipo Cartier\\nKilataje: 14K.\\nPeso: 28.3 grs.', 1425.00, 1425.00,1425.00 , 'null') ;
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (8, 'Subasta de Oro', 'Collar de Oro Torsal\\nKilataje: 10K. Peso: 116 grs.', 3600.00, 3600.00, 3600.00, 'null');
INSERT INTO gala_endeavor_2011_productos (id_prod, nombre, descripcion, costo_actual, costo_inicial, costo_final, last_bidder_id) VALUES (9, 'Subasta de Oro', 'Collar de Oro Barbado\\nKilataje: 10K.\\nPeso: 120 grs.', 3980.00, 3980.00, 3980.00, 'null') ;

INSERT INTO gala_endeavor_2011_alive (id, alive) VALUES (1, true);
